global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'catalog-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8080']
        labels:
          service: 'catalog-api'
          environment: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
